**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [189]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [190]:
arr1 = np.zeros(10)  # null vector of size 10
arr1[4] = 1          # fifth value = 1 (index 4)

print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [216]:
a = int(input("Enter rows (a): "))
b = int(input("Enter cols (b): "))

arr = np.random.randint(1, 100, size=(a, b))  # random array of shape (a, b)

print("\nArray:")
print(arr)

print(f"\nAverage: {arr.mean():.2f}")  # avg of entire array


Array:
[[48 93 16 48 13]
 [91 49 57 88 46]
 [61 96 76 19  6]
 [27 84 81 97 20]]

Average: 55.80


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [192]:
#Code here
def border_array(a, b):
    arr = np.ones((a, b), dtype=int)  # fill all with 1
    arr[1:-1, 1:-1] = 0              # inside values = 0
    return arr

print(border_array(3, 5))
    

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [193]:
#Code here
arr3 = np.linspace(0, 1, 12)[1:-1]  # 0 and 1 excluded
print(arr3)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [194]:
# True identity matrix (3x3) - square only
print("True Identity (3x3):")
print(np.eye(3, dtype=int))

# Rectangular (3x4) - not a true identity matrix
print("\nRectangular Eye (3x4):")
print(np.eye(3, 4, dtype=int))

True Identity (3x3):
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Rectangular Eye (3x4):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [195]:
#Code here

arr5 = np.zeros((5, 5), dtype=int) + np.arange(5)  # broadcast 0-4 across each row

print(arr5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be integer type.

```
point = np.array([2,3])
```


$$d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$

In [199]:
# Random (10,2) coordinate vector
coords = np.random.randint(1, 100, size=(10, 2))

# Given point
point = np.array([2, 3])

# Distance formula: sqrt((x2-x1)^2 + (y2-y1)^2)
distances = np.sqrt(np.sum((coords - point) ** 2, axis=1)).astype(int)

print("Coordinates:")
print(coords)
print("\nGiven Point:", point)
print("\nDistances:", distances)

Coordinates:
[[21 68]
 [75 78]
 [22 24]
 [21 25]
 [41 67]
 [78  3]
 [83 92]
 [49 44]
 [72 99]
 [ 2 10]]

Given Point: [2 3]

Distances: [ 67 104  29  29  74  76 120  62 118   7]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [200]:
arr6 = np.arange(1,337).reshape(6,7,8)
arr6

array([[[  1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16],
        [ 17,  18,  19,  20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29,  30,  31,  32],
        [ 33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48],
        [ 49,  50,  51,  52,  53,  54,  55,  56]],

       [[ 57,  58,  59,  60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69,  70,  71,  72],
        [ 73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88],
        [ 89,  90,  91,  92,  93,  94,  95,  96],
        [ 97,  98,  99, 100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109, 110, 111, 112]],

       [[113, 114, 115, 116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125, 126, 127, 128],
        [129, 130, 131, 132, 133, 134, 135, 136],
        [137, 138, 139, 140, 141, 142, 143, 144],
        [145, 146, 147, 148, 149, 150, 151, 152],
        [153, 154, 155, 156, 157, 158, 159, 16

In [201]:
arr7 = np.arange(6*7*8).reshape(6, 7, 8)
print(arr7[1, 5, 3])  # 99 (0-based → 100th element)

99


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [202]:
#Code here
def reverse_arr(arr):
    return f"elements_count: {arr[::-1].astype(float)}"

test_arr = np.array([1,2,3,4-8,-10])
print(reverse_arr(test_arr))

elements_count: [-10.  -4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [120]:
def element_count(arr):
    return f"elements_count: {arr.size}"  # .size → total elements in array

test_arr1 = np.array([1, 2])   # 2 elements
test_arr2 = np.array([])       # empty array

print(element_count(test_arr1))
print(element_count(test_arr2))

elements_count: 2
elements_count: 0


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [203]:
def softmax(z):
    if not isinstance(z, np.ndarray):  # check if numpy array
        raise TypeError("Input must be a numpy array")
    if z.ndim != 1:                    # check if 1D
        raise ValueError("Input must be a 1D array")

    e_z = np.exp(z - np.max(z))       # stability trick: subtract max
    return e_z / e_z.sum()


# Test
arr = np.array([86.03331084 ,37.7285648 ,48.64908087 ,87.16563062 ,38.40852563 ,37.20006318])
print("Input:   ", arr)
print("Softmax: ", softmax(arr))
print("Sum:     ", softmax(arr).sum())  # always = 1.0

# Error tests
try:
    softmax([1, 2, 3])          # list → error
except TypeError as e:
    print("\nTypeError:", e)

try:
    softmax(np.array([[1,2],[3,4]]))  # 2D → error
except ValueError as e:
    print("ValueError:", e)

Input:    [86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
Softmax:  [2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
Sum:      1.0

TypeError: Input must be a numpy array
ValueError: Input must be a 1D array


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
x= [[0 1 2 3 4]
 [5 6 7 8 9]]

y= [[1 1 1 1 1]
 [1 1 1 1 1]]

z= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [204]:
import numpy as np

def vertical_stack(*arrays):
    # check all inputs are numpy arrays
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError(f"All inputs must be numpy arrays, got {type(arr)}")

    return np.vstack(arrays)  # vertical stack all arrays


# Test 1
a = np.arange(10).reshape(2, 5)
b = np.ones((2, 5), dtype=int)
print("Test 1:")
print(vertical_stack(a, b))

# Test 2
x = np.arange(10).reshape(2, 5)
y = np.ones((2, 5), dtype=int)
z = np.random.rand(2, 5)
print("\nTest 2:")
print(vertical_stack(x, y, z))

# Error test
try:
    vertical_stack(a, [1, 2, 3])  # list → error
except TypeError as e:
    print("\nTypeError:", e)


Test 1:
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Test 2:
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.28263174 0.76752347 0.79489469 0.20800036 0.77477551]
 [0.20721802 0.64714983 0.43906795 0.14653436 0.33016692]]

TypeError: All inputs must be numpy arrays, got <class 'list'>


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [205]:
import numpy as np

def date_array(start, end):
    # check both inputs are strings
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both inputs must be strings")

    start_date = np.datetime64(start)  # convert to numpy date
    end_date   = np.datetime64(end)    # convert to numpy date

    # arange end date exclude karta hai, so +1 day add karo
    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')

    return dates.astype(str)  # convert to string array


# Test 1
print(date_array(start='2020-09-15', end='2020-09-25'))

# Test 2
print(date_array(start='2022-12-01', end='2022-12-06'))

# Test 3
print(date_array(start='2020-11-25', end='2020-11-30'))

# Error test
try:
    date_array(start=2020, end='2020-11-30')  # int → error
except TypeError as e:
    print("\nTypeError:", e)

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06']
['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']

TypeError: Both inputs must be strings


### `Q-14:` Subtract the mean of each row from a matrix.

In [209]:
matrix = np.random.randint(1, 20, size=(4, 5))

result = matrix - matrix.mean(axis=1, keepdims=True)  # subtract each row's mean

print("Original Matrix:")
print(matrix)

print("\nRow Means:")
print(matrix.mean(axis=1))

print("\nAfter Subtracting Row Means:")
print(result)

Original Matrix:
[[ 6 14 18  9 19]
 [16 17 16  9  7]
 [19  2  6  3 12]
 [12 12  1  4 16]]

Row Means:
[13.2 13.   8.4  9. ]

After Subtracting Row Means:
[[-7.2  0.8  4.8 -4.2  5.8]
 [ 3.   4.   3.  -4.  -6. ]
 [10.6 -6.4 -2.4 -5.4  3.6]
 [ 3.   3.  -8.  -5.   7. ]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [210]:
arr = np.random.randint(1, 20, size=(4, 4))

print("Original Array:")
print(arr)

arr[:, [0, 1]] = arr[:, [1, 0]]  # swap col-1 and col-2

print("\nAfter Swapping Column 1 and 2:")
print(arr)

Original Array:
[[ 6 18 15 17]
 [13  1 11  4]
 [18  3  3 10]
 [11  7 19  9]]

After Swapping Column 1 and 2:
[[18  6 15 17]
 [ 1 13 11  4]
 [ 3 18  3 10]
 [ 7 11 19  9]]


### `Q-16:` Replace odd elements in arrays with -1.

In [211]:
arr = np.random.randint(1, 20, size=10)

print("Original:", arr)

arr[arr % 2 != 0] = -1  # replace odd elements with -1

print("After:   ", arr)

Original: [ 8 12 18 17 12 12  2  1  9 10]
After:    [ 8 12 18 -1 12 12  2 -1 -1 10]


### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [212]:
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

result = np.maximum(a, b)  # element-wise max

print("a:     ", a)
print("b:     ", b)
print("Result:", result)

a:      [6 3 1 5 8]
b:      [3 2 1 7 2]
Result: [6 3 1 7 8]


### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [215]:
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)

print("Original Array:")
print(arr1)

# 1. Every alternate column (0, 2, 4)
alternate_cols = arr1[:, ::2]
print("\nAlternate Columns (0, 2, 4):")
print(alternate_cols)

# 2. Normalize using formula: (X - Xmin) / (Xmax - Xmin)
X_min = arr1.min()
X_max = arr1.max()
normalized = (arr1 - X_min) / (X_max - X_min)
print("\nNormalized Array:")
print(normalized.round(4))



Original Array:
[[8140 3724 5679 8312 2678]
 [3108 6965  438 6849 5451]
 [9495 7700 2764 4875 6857]
 [9791 5630 4145 6520 6011]
 [2499 4154 4631 1236 7260]
 [3510 7434 5234 8757 1816]
 [4163 6779 9672 3647 1955]
 [1851 2363 2981 7411 6673]]

Alternate Columns (0, 2, 4):
[[8140 5679 2678]
 [3108  438 5451]
 [9495 2764 6857]
 [9791 4145 6011]
 [2499 4631 7260]
 [3510 5234 1816]
 [4163 9672 1955]
 [1851 2981 6673]]

Normalized Array:
[[0.8235 0.3513 0.5604 0.8419 0.2395]
 [0.2855 0.6979 0.     0.6854 0.536 ]
 [0.9684 0.7764 0.2487 0.4744 0.6863]
 [1.     0.5551 0.3963 0.6503 0.5959]
 [0.2204 0.3973 0.4483 0.0853 0.7294]
 [0.3285 0.748  0.5128 0.8894 0.1473]
 [0.3983 0.678  0.9873 0.3431 0.1622]
 [0.1511 0.2058 0.2719 0.7455 0.6666]]


### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [182]:
def nth_largest(arr, n):
    if n > len(arr):                          # check n <= len(arr)
        raise ValueError(f"n must be <= {len(arr)}")

    return np.sort(arr)[::-1][n - 1]         # sort descending, pick nth


# Test
arr = np.array([12, 34, 40, 7, 1, 0])

print(nth_largest(arr, n=3))  # 12
print(nth_largest(arr, n=1))  # 40
print(nth_largest(arr, n=6))  # 0

12
40
0


### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
a = np.array([1, 2, 3])

part1 = np.repeat(a, 3)  # [1,1,1, 2,2,2, 3,3,3]
part2 = np.tile(a, 3)    # [1,2,3, 1,2,3, 1,2,3]

result = np.concatenate([part1, part2])    # join part1 and part2 into single array

print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
