### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- descending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [124]:
import numpy as np

arr = np.array([[92, 90, 74],
                [ 6, 63, 93],
                [15, 93, 96],
                [70, 60, 48]])


In [125]:
def sort_rowwise(a):
    # sort each row internally
    return np.sort(a, axis=1)

def sort_by_col(a, col=1):
    # sort rows based on given column
    return a[a[:, col].argsort()]

def sort_by_row_max(a, ascending=False):
    # sort rows based on row max
    idx = np.max(a, axis=1).argsort()
    return a[idx[::-1]] if not ascending else a[idx]

def sort_all_elements(a):
    # sort all elements and reshape back
    return np.sort(a.flatten()).reshape(a.shape)

print("Original:\n", arr)
print("\ni.  row wise sort:\n",         sort_rowwise(arr))
print("\nii. sort by 2nd column:\n",    sort_by_col(arr, col=1))
print("\niii. sort by row max (desc):\n", sort_by_row_max(arr))
print("\niv. all elements sorted:\n",   sort_all_elements(arr))

Original:
 [[92 90 74]
 [ 6 63 93]
 [15 93 96]
 [70 60 48]]

i.  row wise sort:
 [[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. sort by 2nd column:
 [[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. sort by row max (desc):
 [[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. all elements sorted:
 [[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
def add_subject(marks, extra_subject):
    # add extra subject as new column
    return np.concatenate([marks, extra_subject.reshape(-1, 1)], axis=1)

def add_students(marks, *records):
    # add new student rows
    new_rows = [r.reshape(1, -1) for r in records]
    return np.concatenate([marks, *new_rows], axis=0)

def add_totals(marks):
    # add total marks as last column
    totals = marks.sum(axis=1, keepdims=True)
    return np.concatenate([marks, totals], axis=1)

def top_students(marks, n=2):
    # sort by total (last column) descending, return top n
    sorted_marks = marks[marks[:, -1].argsort()[::-1]]
    return sorted_marks[:n]


# ── data ──
marks         = np.array([[13, 10,  9, 33],
                           [63, 46, 90, 42],
                           [39, 76, 13, 29],
                           [82,  9, 29, 78],
                           [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92])
rec1          = np.array([77, 83, 98, 95, 89])
rec2          = np.array([92, 71, 52, 61, 53])

# ── call functions ──
print("Original:\n", marks)

marks = add_subject(marks, extra_subject)
print("\ni.  After adding extra subject:\n", marks)

marks = add_students(marks, rec1, rec2)
print("\nii. After adding 2 students:\n", marks)

marks = add_totals(marks)
print("\niii. After adding total column:\n", marks)

print("\niv. Top 2 students:\n", top_students(marks))

Original:
 [[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]]

i.  After adding extra subject:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

ii. After adding 2 students:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

iii. After adding total column:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

iv. Top 2 students:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [122]:
import numpy as np

arr = np.array([[1, 2, 3, 3, 1, 1],
                [0, 9, 1, 2, 8, 8],
                [1, 2, 3, 8, 8, 8],
                [1, 2, 3, 3, 1, 1]])

# avoid repetition — functions banao
def unique_rows(a):
    return np.unique(a, axis=0)

def unique_cols(a):
    return np.unique(a, axis=1)

choice = input("Enter your choice (row / col / both): ").strip().lower()

if choice == "row":
    print("Row Wise:\n", unique_rows(arr))

elif choice == "col":
    print("Col Wise:\n", unique_cols(arr))

elif choice == "both":
    print("Row Wise:\n", unique_rows(arr))
    print("\nCol Wise:\n", unique_cols(arr))

else:
    print("Invalid input! Enter: row / col / both")

Row Wise:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


### `Q-4:` Flip given 2-D array along both axes at the same time.

In [110]:
# original array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original:\n", arr)

# flip along both axes (rows + columns)
flipped = np.flip(arr)
print("\nFlipped (both axes):\n", flipped)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped (both axes):
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [111]:
# given array and threshold
arr = np.array([[1,  2,  3,  4, 5],
                [10, -3, 30,  4, 5],
                [3,  2,  5, -4, 5],
                [9,  7,  3,  6, 5]])

X = 6

# check each row — True if any element > X
# np.where returns indices where condition is True
row_nums = np.where(np.any(arr > X, axis=1))[0]

print("Row numbers having element > 6:", row_nums)


Row numbers having element > 6: [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)


In [ ]:
def flatten_arrays(*arrays):
    # combine all arrays into one array of arrays
    arr = np.array(arrays, dtype=object)
    print("Original:", arr)

    # join all into one flat 1D array
    flat = np.concatenate(arr)
    print("Flattened:", flat)
    return flat

# call the function
flatten_arrays(np.arange(3), np.arange(3, 7), np.arange(7, 10))

Original: [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]

np.concatenate : [0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
def remove_min_max(arr):
    print("Original shape:", arr.shape)
    print("Min:", arr.min(), "| Max:", arr.max())

    # flatten (1,200) → (200,)
    flat = arr.flatten()

    # find and remove min & max elements
    flat = np.delete(flat, np.where((flat == flat.min()) | (flat == flat.max())))

    print("\nNew shape:", flat.shape)
    print("New Min:", flat.min(), "| New Max:", flat.max())
    print("\nArray:\n", flat)
    return flat

# call the function
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
remove_min_max(arr)

Original shape: (1, 200)
Min: 103 | Max: 998
New shape: (198,)
New Min: 117 | New Max: 997

Array:
 [448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
def clip_sort_cumsum(arr, low=100, high=200):
    print("Original:\n", arr)

    # replace values below low with low, above high with high
    clipped = np.clip(arr, low, high)
    print(f"\nAfter clip ({low}–{high}):\n", clipped)

    # sort in ascending order
    sorted_arr = np.sort(clipped)
    print("\nSorted:\n", sorted_arr)

    # each element = sum of all previous elements + itself
    cumsum = np.cumsum(sorted_arr)
    print("\nCumulative sum:\n", cumsum)
    return cumsum

# call the function
np.random.seed(42)
arr = np.random.randint(100, 700, 20)
clip_sort_cumsum(arr)

Original:
 [202 535 370 206 171 120 221 566 314 430 558 187 472 199 230 408 443 591
 513 485]

After clip (100–200):
 [200 200 200 200 171 120 200 200 200 200 200 187 200 199 200 200 200 200
 200 200]

Sorted:
 [120 171 187 199 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200]

Cumulative sum:
 [ 120  291  478  677  877 1077 1277 1477 1677 1877 2077 2277 2477 2677
 2877 3077 3277 3477 3677 3877]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [123]:
def percentile_analysis(arr):
    # round to 3 decimal places
    arr = np.round(arr, 3)
    print("Array:\n", arr)

    # min and max
    print("\nMin value      :", arr.min())
    print("Max value      :", arr.max())

    # 0th and 100th percentile = min and max
    p0   = np.percentile(arr, 0)
    p100 = np.percentile(arr, 100)

    # 50th and 51st percentile
    p50  = np.percentile(arr, 50)
    p51  = np.percentile(arr, 51)

    print("\n0th  percentile:", p0,   "== Min?", p0   == arr.min())
    print("100th percentile:", p100, "== Max?", p100 == arr.max())

    print("\n50th percentile :", p50)
    print("51st percentile :", p51)

    # difference between 51st and 50th
    print("Difference      :", round(p51 - p50, 5))

# call the function
np.random.seed(42)
arr = np.random.random(20)
percentile_analysis(arr)

Array:
 [0.375 0.951 0.732 0.599 0.156 0.156 0.058 0.866 0.601 0.708 0.021 0.97
 0.832 0.212 0.182 0.183 0.304 0.525 0.432 0.291]

Min value      : 0.021
Max value      : 0.97

0th  percentile: 0.021 == Min? True
100th percentile: 0.97 == Max? True

50th percentile : 0.40349999999999997
51st percentile : 0.41433
Difference      : 0.01083
